Attribute VB_Name = "modSettings"
Option Explicit

Public SettingsFile As String
Public Declare Sub Sleep Lib "kernel32.dll" (ByVal dwMilliseconds As Long)

Public Type GlobalSettings
    UserName As String
    blDebug As Boolean
    DisableLan As Boolean
    BackgroundPath As String
    ShowIcons As Boolean
    IconSize As Integer
    ChatTextSize As Integer
    IconTextSize As Integer
    ChatTextColor As Long
    IconTextColor As Long
    ChatBGColor As Long
    LanBGColor As Long
    DockChat As Boolean
    ShowChat As Boolean
    LogChat As Boolean
    Jason As Boolean
    KeyGen As Integer
    AutoUpdate As Boolean
    ScanAtStartup As Boolean
    SameVersion As Boolean
    ShowStatus As Boolean
    AcceptPrivateChat As Boolean
    LanAdmin As Boolean
    AltChatType As Boolean
    MonitorGame As Boolean 'monitor when a game's EXE has exited to bring up the launcher again.
    CurrentGame As Integer
    AllowCommands As Boolean
    MinimizeAfterLaunch As Boolean
    UniqueID As String
    CurrentIP As String
    MainWindowWidth As Long
    MainWindowHeight As Long
    ChatWindowWidth As Long
    ChatWindowHeight As Long
End Type

Public Settings As GlobalSettings

Public Sub SaveSettings()
Dim strSettings As String

With Settings
AddToString "// Settings file generated by LanParty v" & GetAppVersion & " by Dragoon //", strSettings
AddToString "", strSettings

AddToString "UserName " & .UserName, strSettings
AddToString "Debug " & .blDebug, strSettings
AddToString "DisableLan " & .DisableLan, strSettings
AddToString "BackgroundPath " & .BackgroundPath, strSettings
AddToString "ShowIcons " & .ShowIcons, strSettings
AddToString "IconSize " & .IconSize, strSettings
AddToString "ChatTextSize " & .ChatTextSize, strSettings
AddToString "IconTextSize " & .IconTextSize, strSettings
AddToString "ChatTextColor " & .ChatTextColor, strSettings
AddToString "IconTextColor " & .IconTextColor, strSettings
AddToString "ChatBGColor " & .ChatBGColor, strSettings
AddToString "LanBGColor " & .LanBGColor, strSettings
AddToString "UniqueID " & .UniqueID, strSettings
AddToString "MinimizeAfterLaunch " & .MinimizeAfterLaunch, strSettings
AddToString "AllowCommands " & .AllowCommands, strSettings
AddToString "MonitorGame " & .MonitorGame, strSettings
AddToString "ShowChat " & .ShowChat, strSettings
AddToString "DockChat " & .DockChat, strSettings
AddToString "LogChat " & .LogChat, strSettings
AddToString "ShowStatus " & .ShowStatus, strSettings
AddToString "ImJason " & .Jason, strSettings
AddToString "KeyGen " & .KeyGen, strSettings
AddToString "AutoUpdate " & .AutoUpdate, strSettings
AddToString "ScanAtStartup " & .ScanAtStartup, strSettings
AddToString "AcceptPrivateChat " & .AcceptPrivateChat, strSettings
AddToString "SameVersion " & .SameVersion, strSettings
AddToString "AltChatType " & .AltChatType, strSettings
AddToString "MainWindowWidth " & .MainWindowWidth, strSettings
AddToString "MainWindowHeight " & .MainWindowHeight, strSettings
AddToString "ChatWindowWidth " & .ChatWindowWidth, strSettings
AddToString "ChatWindowHeight " & .ChatWindowHeight, strSettings

AddToString "", strSettings
AddToString "// Settings file generated on " & IIf(IsHost64Bit, "64-bit", "32-bit") & " " & NativeGetVersion & " //", strSettings
WriteFile strSettings, SettingsFile, True

End With

End Sub

'loadsettings
Public Sub InitializeSettings()
Dim strSettings As String

SettingsFile = App.Path & "\Settings.txt"

strSettings = LoadFile(SettingsFile)

If LenB(strSettings) < 1 Then
    'initialize default settings here.
    With Settings
    .blDebug = False
    .AllowCommands = False
    .MinimizeAfterLaunch = True
    .MonitorGame = True
    .IconSize = 2
    .ShowChat = True
    .DockChat = True
    .KeyGen = 5
    .AcceptPrivateChat = False
    .SameVersion = False
    .AutoUpdate = False
    .ScanAtStartup = True
    .ShowStatus = True
    .LogChat = False
    '.UserName = "LanScrub"
    .ChatTextSize = 8
    .IconTextSize = 8
    .ChatTextColor = 0
    .IconTextColor = 0
    .ChatBGColor = 16777215
    .LanBGColor = -2147483633
    .ChatWindowHeight = 2775
    .ChatWindowWidth = 9800
    .MainWindowHeight = 6005
    .MainWindowWidth = 9800
    .ShowIcons = True
    .BackgroundPath = vbNullString
    End With

Else

Dim lines() As String
lines = Split(strSettings, vbNewLine)

If UBound(lines) > 1 Then
    Dim i As Long
    Dim Line As String
    Dim strSwitch As String
    Dim strData As String
    For i = 0 To UBound(lines)
        Line = Trim$(lines(i))
        
        If Not Left$(Line, 2) = "//" Then 'Next 'skip comments
            If Not LenB(Line) < 1 Then
                strSwitch = LCase$(Split(Line, " ")(0))
                strData = Trim$(Right$(Line, Len(Line) - Len(strSwitch)))
                
                Select Case strSwitch
                
                Case "username"
                'Mid(line, Len("username") + 2)
                If VerifyKeyAsString(Trim$(strData)) Then Settings.UserName = Trim$(strData)
                
                Case "debug"
                Settings.blDebug = IIf(LCase$(strData) = "true", True, False)
                
                Case "disablelan"
                Settings.DisableLan = IIf(LCase$(strData) = "true", True, False)
                
                Case "dockchat"
                Settings.DockChat = IIf(LCase$(strData) = "true", True, False)
                
                Case "showchat"
                Settings.ShowChat = IIf(LCase$(strData) = "true", True, False)
                
                Case "logchat"
                Settings.LogChat = IIf(LCase$(strData) = "true", True, False)
                                
                Case "showstatus"
                Settings.ShowStatus = IIf(LCase$(strData) = "true", True, False)
                
                Case "imjason"
                Settings.Jason = IIf(LCase$(strData) = "true", True, False)
                
                Case "keygen"
                Settings.KeyGen = CInt(strData)
                
                Case "autoupdate"
                Settings.AutoUpdate = IIf(LCase$(strData) = "true", True, False)
                
                Case "scanatstartup"
                Settings.ScanAtStartup = IIf(LCase$(strData) = "true", True, False)
                
                Case "sameversion"
                Settings.SameVersion = IIf(LCase$(strData) = "true", True, False)
                
                Case "acceptprivatechat"
                Settings.AcceptPrivateChat = IIf(LCase$(strData) = "true", True, False)
                
                Case "altchattype"
                Settings.AltChatType = IIf(LCase$(strData) = "true", True, False)
                
                Case "showicons"
                Settings.ShowIcons = IIf(LCase$(strData) = "true", True, False)
                
                Case "monitorgame"
                Settings.MonitorGame = IIf(LCase$(strData) = "true", True, False)
                
                Case "allowcommands"
                Settings.AllowCommands = IIf(LCase$(strData) = "true", True, False)
                
                Case "minimizeafterlaunch"
                Settings.MinimizeAfterLaunch = IIf(LCase$(strData) = "true", True, False)
                
                Case "backgroundpath"
                If LenB(strData) > 0 Then
                    If FileExists(FixFilePath(strData)) Then
                        Settings.BackgroundPath = strData
                    Else
                        MsgBox "BackgroundPath is invalid; unable to locate " & strData & "." & vbNewLine & vbNewLine & _
                        "The file will not be loaded.", vbCritical, "Unable to load picture!"
                    End If
                End If
                
                Case "uniqueid"
                Settings.UniqueID = strData
                
                Case "iconsize"
                '& .IconSize, strSettings
                Settings.IconSize = CInt(strData)
                
                Case "chattextsize"
                Settings.ChatTextSize = CInt(strData)
                
                Case "icontextsize"
                Settings.IconTextSize = CInt(strData)

                Case "chattextcolor"
                Settings.ChatTextColor = CLng(strData)
                
                Case "icontextcolor"
                Settings.IconTextColor = CLng(strData)
                
                Case "chatbgcolor"
                Settings.ChatBGColor = CLng(strData)
                
                Case "lanbgcolor"
                Settings.LanBGColor = CLng(strData)
                
                Case "mainwindowwidth"
                '& .MainWindowWidth, strSettings
                Settings.MainWindowWidth = CLng(strData)
                
                Case "mainwindowheight"
                '& .MainWindowHeight, strSettings
                Settings.MainWindowHeight = CLng(strData)
                
                Case "chatwindowwidth"
                '& .ChatWindowWidth, strSettings
                Settings.ChatWindowWidth = CLng(strData)
                
                Case "chatwindowheight"
                Settings.ChatWindowHeight = CLng(strData)
                
                Case Else
                    AddDebug "Unknown case: " & Line, True
                
                End Select
            End If
        End If
    Next i
End If


End If

If Settings.ChatTextSize < 6 Then Settings.ChatTextSize = 8
If Settings.IconTextSize < 6 Then Settings.IconTextSize = 8
'If Settings.ChatBGColor = 0 Then Settings.ChatBGColor = 16777215
'If Settings.ChatTextColor = 0 Then Settings.ChatTextColor = 0
'If Settings.IconTextColor = 0 Then Settings.IconTextColor = 0

'check for valid username.
If LenB(Settings.UserName$) = 0 Then
    frmSettings.Show vbModal
    Unload frmSettings
    'RefreshSettings
    'frmMain.RefreshBackground
    Exit Sub
End If

If LenB(Settings.UserName$) = 0 Then MsgBox "You need to try again and next time.. type a User Name into the little box.", vbCritical, "C'mon.. really?": frmMain.DoExit

'RefreshSettings

End Sub

Public Sub RefreshSettings()
'On Error Resume Next
With frmMain
If Settings.DisableLan Then DisableNetwork
.mnuMonitorGame.Checked = Settings.MonitorGame
.mnuAllowCommands.Checked = Settings.AllowCommands
.mnuLanChat.Checked = Settings.ShowChat
.mnuDockChat.Checked = Settings.DockChat
If blBootComplete = True Then
    If Settings.ShowChat Then If Settings.DockChat = True Then frmChat.DockChat
    frmChat.Visible = Settings.ShowChat
    .SetIconsTo Settings.IconSize
End If
.Width = Settings.MainWindowWidth
.Height = Settings.MainWindowHeight
frmChat.txtChat.BackColor = Settings.ChatBGColor
frmChat.txtChat.ForeColor = Settings.ChatTextColor
frmChat.txtChat.FontSize = Settings.ChatTextSize
frmChat.lstUsers.BackColor = Settings.ChatBGColor
frmChat.txtEnter.BackColor = Settings.ChatBGColor
frmChat.txtEnter.ForeColor = Settings.ChatTextColor
.picContainer.BackColor = Settings.LanBGColor
.BackColor = Settings.LanBGColor
End With

ColorIconText

If frmChat.Visible = True Then frmChat.Resize
'With frmChat
'    .Width = Settings.ChatWindowWidth
'    .Height = Settings.ChatWindowHeight
'End With

End Sub

Public Sub ColorIconText()
On Error GoTo Escape

Dim i As Integer
For i = 1 To UBound(Game)
        frmMain.lblIcon(i).FontSize = Settings.IconTextSize
        frmMain.lblIcon(i).ForeColor = Settings.IconTextColor
        DoEvents
Next
Exit Sub

Escape:
err.Clear
End Sub
